#!/usr/bin/env python3
"""Build the small, reproducible bitmap alphabet used by report preview PNGs.

Development only: Python 3 + Pillow, with an OFL Noto Sans SC font supplied by
--font. Production uses the committed glyphs and requires neither dependency.
"""
import argparse
import base64
import hashlib
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--font", type=Path, required=True)
parser.add_argument("--output", type=Path, default=Path("deploy/cloudflare-worker/src/share-font.js"))
args = parser.parse_args()
chinese = (
    "北京天津河北山西内蒙古辽宁吉林黑龙江上海江苏浙江安徽福建江西山东河南湖北湖南广东广西海南"
    "重庆四川贵州云南西藏陕西甘肃青海宁夏新疆台湾香港澳门"
    "测速报告单线程档位地区未知电信联通移动延迟上传下载失败暂无数据打开查看完整结果"
    "共个图中为时间北京时间与关联相差超过分钟无法确认说明已展示不代表峰值"
    "运营商本表示达到所选档位未限速多个检测"
    "，。：；、·｜✓（）"
)
characters = sorted(set(chr(c) for c in range(32, 127)) | set(chinese))
atlas = {}
for size in (20, 24, 32, 40):
    font = ImageFont.truetype(str(args.font), size)
    if font.get_variation_axes():
        font.set_variation_by_axes([500])
    glyphs = {}
    for ch in characters:
        left, top, right, bottom = font.getbbox(ch, anchor="ls")
        width, height = right - left, bottom - top
        image = Image.new("L", (width, height))
        ImageDraw.Draw(image).text((-left, -top), ch, font=font, fill=255, anchor="ls")
        pixels = [round(p / 17) for p in image.tobytes()]
        encoded = bytearray()
        index = 0
        while index < len(pixels):
            value, count = pixels[index], 1
            while count < 16 and index + count < len(pixels) and pixels[index + count] == value:
                count += 1
            encoded.append(((count - 1) << 4) | value)
            index += count
        glyphs[ch] = [width, height, round(font.getlength(ch)), left, top,
                      base64.b64encode(encoded).decode("ascii")]
    atlas[size] = glyphs
digest = hashlib.sha256(args.font.read_bytes()).hexdigest()
header = ("// Generated by tools/build-share-font.py; do not edit by hand.\n"
          "// Noto Sans SC glyphs, SIL OFL 1.1; see SHARE-FONT-LICENSE.txt.\n"
          f"// Source font SHA256: {digest}\n")
args.output.write_text(header + "export const SHARE_FONT = " +
                       json.dumps(atlas, ensure_ascii=False, separators=(",", ":")) + ";\n")
print(f"Built {len(characters)} glyphs at four sizes: {args.output.stat().st_size} bytes")
